// <auto-generated />
using System;
using LoyihaniBoshqarishTizimliDasturlash.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyihaniBoshqarishTizimliDasturlash.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230916091829_initialMig")]
    partial class initialMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("JobId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeveloperTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperTypeId");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.DeveloperType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeveloperTypes");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Assignment", b =>
                {
                    b.HasOne("LoyihaniBoshqarishTizimliDasturlash.Models.Developer", "Developer")
                        .WithMany("Assignments")
                        .HasForeignKey("DeveloperId");

                    b.HasOne("LoyihaniBoshqarishTizimliDasturlash.Models.Job", null)
                        .WithMany("Assignments")
                        .HasForeignKey("JobId");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Developer", b =>
                {
                    b.HasOne("LoyihaniBoshqarishTizimliDasturlash.Models.DeveloperType", "DeveloperType")
                        .WithMany()
                        .HasForeignKey("DeveloperTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeveloperType");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Image", b =>
                {
                    b.HasOne("LoyihaniBoshqarishTizimliDasturlash.Models.Assignment", "Assignment")
                        .WithMany("Images")
                        .HasForeignKey("AssignmentId");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Assignment", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Developer", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("LoyihaniBoshqarishTizimliDasturlash.Models.Job", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
